### ISSUE TITLE
Missing flex-basis

### ISSUE THREAD

**Issue by jessep** [tachyons-css/tachyons-flexbox#4]
Just wondering about flex basis. Hard to make a responsive layout without it. Is your opinion that one should just use the float utils for such layouts? Am I missing some obvious trick?

**Comment by ixley** [comment]
I was also curious why specifics for `flex-grow`, `flex-shrink`, and `flex-basis` were left out. I assume it was intentional, but am curious about the specific rationale. In terms of keeping the library from becoming too bloated, I imagine there has to be a cutoff at some point. 

@jessep Have you tried seeing whether you can accomplish what you need with a combination of `.flex-auto` (`flex: 1 1 auto;`) and `.flex-none` (`flex: none; // 0 0 auto;`)?

**Comment by jessep** [comment]
Yeah, I did realize I could use flex-auto, thanks

Partially based on this, I read through the whole stylesheet today, which
was exceptionally helpful.

**Comment by philipyoungg** [comment]
@ixley @jessep 

Regarding flex-auto, there's a bug on older browser (either IE9 or Android below Jelly Bean) that ignore this value.

Instead of `flex-auto: 1 100px;`
Solution: use `flex-grow: 1; min-width:100px; width: 100%;`

Source: I have encountered these issue from my previous project.

**Comment by FateRiddle** [comment]
Why do we not having those properties(flex-basis, flex-grow, flex-shrink)? At least a 'flex: x y z' is required imo.

**Comment by mrkhdly** [comment]
Tachyons v5 will become a monorepo so this issue is being closed, if the issue is still relevant please open an issue with the main repo https://github.com/tachyons-css/tachyons/issues/new & link to this one
